# Streamlit Community Cloud 배포용 환경변수 설정
# 이 파일은 실제 배포 시 Streamlit Cloud에서 Secrets로 설정해야 합니다.

# OpenAI API 설정
OPENAI_API_KEY = "your_openai_api_key_here"
OPENAI_MODEL_NAME = "gpt-4o-mini"

# 프롬프트 및 데이터 파일 경로
THERAPY_SYSTEM_PROMPT_PATH = "prompts/therapy_system_prompt.md"
PARTICIPANTS_JSON_PATH = "data/participants.json"

# 로그 설정 (Streamlit Cloud용)
LOG_LEVEL = "INFO"

# 사용 참고:
# 1. Streamlit Community Cloud에서 App Settings > Secrets로 이동
# 2. 위 내용을 붙여넣고 실제 API 키로 변경
# 3. 각 변수명과 값은 따옴표 없이 입력
# 예시: OPENAI_API_KEY = sk-xxxxxxxxxxxxxxxx